name: Deploy VitePress site to Cloudflare Pages
on:
  # Runs on pull requests.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy PR to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: bun install
      - name: Build with VitePress
        run: bun run build
      - name: Publish
        id: cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: discuit-docs-pr
          directory: docs/.vitepress/dist
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
      - name: Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### Your deployment preview is ready!

            | Name               | Link                                      |
            | ------------------ | ----------------------------------------- |
            | Latest commit      | ${{ github.event.pull_request.head.sha }} |
            | Preview URL        | ${{ steps.cloudflare.outputs.url }}       |

          comment_tag: deployment
